### ISSUE TITLE
Build Failures with the latest HEAD and java 1.8

### ISSUE THREAD

**Issue by SEJeff** [mesos/kafka#123]
``` bash
jschroeder@omniscience:~/git/ATLAS/kafka-mesos-framework/kafka (master *)$ ./gradlew jar --stacktrace
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestScala UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test

ly.stealth.mesos.kafka.RebalancerTest > start FAILED
    org.I0Itec.zkclient.exception.ZkTimeoutException at RebalancerTest.scala:56

ly.stealth.mesos.kafka.TopicsTest > fairAssignment FAILED
    org.I0Itec.zkclient.exception.ZkTimeoutException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.TopicsTest > addTopic FAILED
    java.lang.IllegalStateException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.TopicsTest > validateOptions FAILED
    java.lang.IllegalStateException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.TopicsTest > updateTopic FAILED
    java.lang.IllegalStateException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.TopicsTest > getTopics FAILED
    java.lang.IllegalStateException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.TopicsTest > Topic_toJson_fromJson FAILED
    java.lang.IllegalStateException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.TopicsTest > getTopic FAILED
    java.lang.IllegalStateException at TopicsTest.scala:14
    java.lang.NullPointerException at TopicsTest.scala:21

ly.stealth.mesos.kafka.CliTest > broker_remove FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > broker_update FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > topic_list FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > broker_start_stop_timeout FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > connection_refused FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > usage_errors FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > help FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > topic_add FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > broker_start_stop FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > broker_list FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > topic_rebalance FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > topic_update FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.CliTest > broker_add FAILED
    java.lang.IllegalStateException at CliTest.scala:38
    java.lang.NullPointerException at CliTest.scala:46

ly.stealth.mesos.kafka.ExprTest > expandTopics FAILED
    java.lang.IllegalStateException at ExprTest.scala:12
    java.lang.NullPointerException at ExprTest.scala:18

ly.stealth.mesos.kafka.ExprTest > expandBrokers_attributes FAILED
    java.lang.IllegalStateException at ExprTest.scala:12
    java.lang.NullPointerException at ExprTest.scala:18

ly.stealth.mesos.kafka.ExprTest > expandBrokers FAILED
    java.lang.IllegalStateException at ExprTest.scala:12
    java.lang.NullPointerException at ExprTest.scala:18

ly.stealth.mesos.kafka.HttpServerTest > broker_remove FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > broker_update FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > jar_download FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > topic_list FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > kafka_download FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > broker_add_range FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > topic_add FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > broker_start_stop FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > broker_list FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > topic_rebalance FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > topic_update FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

ly.stealth.mesos.kafka.HttpServerTest > broker_add FAILED
    java.lang.IllegalStateException at HttpServerTest.scala:36
    java.lang.NullPointerException at HttpServerTest.scala:43

104 tests completed, 36 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/jschroeder/git/ATLAS/kafka-mesos-framework/kafka/out/gradle/reports/tests/index.html

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:296)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/jschroeder/git/ATLAS/kafka-mesos-framework/kafka/out/gradle/reports/tests/index.html
    at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1111)
    at org.gradle.api.tasks.testing.Test.executeTests(Test.java:542)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:570)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:553)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 47 more


BUILD FAILED

Total time: 1 mins 5.026 secs
```

This is with java 1.8

``` bash
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

The same build succeeds when using either of these:

``` bash
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.1.el7_1-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

I've also verified that nothing is listening on any ports that should interfere:

``` bash
# lsof -nPi | grep LISTEN | sort
master     2314       root   13u  IPv4    34857      0t0  TCP 127.0.0.1:25 (LISTEN)
rpcbind    1195        rpc    9u  IPv4    13596      0t0  TCP *:111 (LISTEN)
rpc.statd 27493    rpcuser    9u  IPv4    16131      0t0  TCP *:38722 (LISTEN)
splunkd    7922       root    4u  IPv4 76563644      0t0  TCP *:8089 (LISTEN)
sshd      27606       root    3u  IPv4    70666      0t0  TCP *:22 (LISTEN)
ypbind    20969       root    5u  IPv4 21821403      0t0  TCP *:798 (LISTEN)
```

**Comment by tobilg** [comment]
+1 

I'm seeing the "ly.stealth.mesos.kafka.CliTest > broker_add FAILED" error as well on `1.8.0_60`

**Comment by dmitrypekar** [comment]
@tobilg @SEJeff 
Unfortunately can't reproduce it locally on 1.8 u60.

Could you also provide 2 additional items:
- what exact release / OS do you use;
- zip and attach $project/out/gradle/reports folder;

This should provide enough info for me to be able to reproduce that issue.

**Comment by SEJeff** [comment]
RHEL 7.1 / java 1.8.0_45 see:

``` bash
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.1 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.1:GA:workstation"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.1"
```

The test results can be [downloaded here](http://www.digitalprognosis.com/tests.zip). Should be reproducible with CentOS 7.1 as well, but I'm using a workstation similar to the servers that I run mesos on.

**Comment by dmitrypekar** [comment]
Hi @SEJeff, cc @tobilg  

Thank you for your feedback. The reason of failing tests was ZK server trying to bind to a static port, that is used by your environment. Pushed changes to test code to use available local port, detected at runtime.

This should fix the problem with tests. Please check that on latest master branch and close the issue if the problem is fixed. If not (should not happen), please attach new tests results as you did before.

**Comment by dmitrypekar** [comment]
Hi @SEJeff 
Could you please report me did the change helped? 
I am going to close a ticket in 10 days if no response would be available.

**Comment by SEJeff** [comment]
@dmitrypekar confirmed fixed. Thanks!

**Comment by bigdata-user** [comment]
I successfully solve this problem!

**Comment by bakre-ha** [comment]
HI everybody, 
I have a similar problem with my ubuntu 16 machine. Could you help me?

:compileJava UP-TO-DATE
:compileScala
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:compileTestScala
[ant:scalac] Element '/home/bsuccess/Work/BSKERNEL/Mesos/kafka/out/gradle/resources/main' does not exist.
:processTestResources UP-TO-DATE
:testClasses
:test

ly.stealth.mesos.kafka.CliTest > connection_refused FAILED
    java.lang.AssertionError at CliTest.scala:371

ly.stealth.mesos.kafka.CliTest > broker_add FAILED
    java.lang.AssertionError at CliTest.scala:377

95 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':test'.
  
  > There were failing tests. See the report at: file:///home/bsuccess/Work/BSKERNEL/Mesos/kafka/out/gradle/reports/tests/index.html
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 5.335 secs
