### ISSUE TITLE
Support for snappy?

### ISSUE THREAD

**Issue by DarinJ** [mesos/kafka#147]
I've been attempting to use this framework, it works fine until snappy compression (works fine with gzip or none) is enabled.  

I confirmed I have the proper c++ libs installed for snappy (`ldd -v libsnappyjava.so` after extracting from jar), and attempted to use snappy 1.1.1.3 which has statically linked libraries as well.  Tested snappy with the same version of kafka on the same system w/o the framework and all was well.

In stderr I get:

```
Could not load 'org-xerial-snappy.properties' from classpath: java.lang.NullPointerException
java.lang.NullPointerException
    at org.xerial.snappy.SnappyLoader.getRootClassLoader(SnappyLoader.java:147)
    at org.xerial.snappy.SnappyLoader.injectSnappyNativeLoader(SnappyLoader.java:256)
    at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:227)
    at org.xerial.snappy.Snappy.<clinit>(Snappy.java:48)
    at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:351)
    at org.xerial.snappy.SnappyInputStream.rawRead(SnappyInputStream.java:159)
    at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:142)
    at java.io.InputStream.read(InputStream.java:101)
    at kafka.message.ByteBufferMessageSet$$anonfun$decompress$1.apply$mcI$sp(ByteBufferMessageSet.scala:68)
    at kafka.message.ByteBufferMessageSet$$anonfun$decompress$1.apply(ByteBufferMessageSet.scala:68)
    at kafka.message.ByteBufferMessageSet$$anonfun$decompress$1.apply(ByteBufferMessageSet.scala:68)
    at scala.collection.immutable.Stream$.continually(Stream.scala:1129)
    at kafka.message.ByteBufferMessageSet$.decompress(ByteBufferMessageSet.scala:68)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNextOuter(ByteBufferMessageSet.scala:178)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:191)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:145)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
    at scala.collection.AbstractIterator.to(Iterator.scala:1157)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
    at kafka.message.ByteBufferMessageSet.assignOffsets(ByteBufferMessageSet.scala:219)
    at kafka.log.Log.liftedTree1$1(Log.scala:252)
    at kafka.log.Log.append(Log.scala:251)
    at kafka.cluster.Partition.appendMessagesToLeader(Partition.scala:354)
    at kafka.server.KafkaApis$$anonfun$appendToLocalLog$2.apply(KafkaApis.scala:376)
    at kafka.server.KafkaApis$$anonfun$appendToLocalLog$2.apply(KafkaApis.scala:366)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scal
```

In stdout

```
[2015-11-11 14:37:43,955] ERROR [KafkaApi-1] Error processing ProducerRequest with correlation id 3221 from client PROD-45a5477c-2fd1-4bb4-9460-56838a9505e2 on partition [t1,4] (kafka.server.KafkaApis)
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null
    at org.xerial.snappy.SnappyLoader.injectSnappyNativeLoader(SnappyLoader.java:297)
    at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:227)
    at org.xerial.snappy.Snappy.<clinit>(Snappy.java:48)
    at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:351)
    at org.xerial.snappy.SnappyInputStream.rawRead(SnappyInputStream.java:159)
    at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:142)
    at java.io.InputStream.read(InputStream.java:101)
    at kafka.message.ByteBufferMessageSet$$anonfun$decompress$1.apply$mcI$sp(ByteBufferMessageSet.scala:68)
    at kafka.message.ByteBufferMessageSet$$anonfun$decompress$1.apply(ByteBufferMessageSet.scala:68)
    at kafka.message.ByteBufferMessageSet$$anonfun$decompress$1.apply(ByteBufferMessageSet.scala:68)
    at scala.collection.immutable.Stream$.continually(Stream.scala:1129)
    at kafka.message.ByteBufferMessageSet$.decompress(ByteBufferMessageSet.scala:68)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNextOuter(ByteBufferMessageSet.scala:178)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:191)
    at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:145)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
    at scala.collection.AbstractIterator.to(Iterator.scala:1157)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
    at kafka.message.ByteBufferMessageSet.assignOffsets(ByteBufferMessageSet.scala:219)
    at kafka.log.Log.liftedTree1$1(Log.scala:252)
    at kafka.log.Log.append(Log.scala:251)
    at kafka.cluster.Partition.appendMessagesToLeader(Partition.scala:354)
    at kafka.server.KafkaApis$$anonfun$appendToLocalLog$2.apply(KafkaApis.scala:376)
    at kafka.server.KafkaApis$$anonfun$appendToLocalLog$2.apply(KafkaApis.scala:366)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at kafka.server.KafkaApis.appendToLocalLog(KafkaApis.scala:366)
    at kafka.server.KafkaApis.handleProducerRequest(KafkaApis.scala:292)
    at kafka.server.KafkaApis.handle(KafkaApis.scala:185)
    at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:42)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmitrypekar** [comment]
Hi @DarinJ 
Thank you for posting the problem.

For now it seems that I have not enough info to be able to reproduce the problem.
I've tried several options, but it worked correctly on my mesos cluster.

Could you please provide following additional details:
1. what version of kafka-mesos are you using?
2. what version of kafka?
3. what version of jdk?
4. what version of mesos?
5. what version of OS?
6. what is the deployment: how many brokers, how many topics/partitions, what are the producers settings (paste a config or a code snippet) and what kind of producer API are you using?
7. are kafka and producer versions the same?

Sorry for asking a lot of questions, but providing this additional info would help me to reproduce and fix this issue correctly.

Thanks in advance.

**Comment by DarinJ** [comment]
@dmitrypekar Thanks for responding
1. v0.9.2.0 (tag)
2. 0.8.1.1 (same as gradle deep)
3. 1.7 oracle + 1.7 openjdk
4 22.1 and 24.0
5. CentOS 6 and Ubuntu 14
6. 5 brokers 2 topics 10 partitions and  2 brokers 1 topic 4 partitions (setting them brokers to be on unique hosts).  Code from memory (Will edit later with exact info):

```
        Properties props = new Properties();
        props.put("metadata.broker.list", "host1:port1,host2:port2");
        props.put("client.id", "blah")
        props.put("compression.codec", "snappy"); //gzip and none fix the error
        props.put("request.required.acks", "1");
        props.put("producer.type", "sync");
        props.put("request.timeout.ms", "10000");
        props.put("message.send.max.retries", "1");
```
1. Originally producer was 0.8.2.2 but recompiled to 0.8.1.1

**Comment by dmitrypekar** [comment]
@DarinJ Reproduced. Working on the fix.

**Comment by dmitrypekar** [comment]
@DarinJ Fixed in master. Please verify and reopen this ticket if this doesn't solve the problem.
