### ISSUE TITLE
Support of Kafka 0.9.0.0

### ISSUE THREAD

**Issue by sherzberg** [mesos/kafka#162]
Are there plans for using Kafka 0.9.0.0? What will the upgrade path be for current 0.8 brokers?

**Comment by altvnk** [comment]
+1

**Comment by JohnOmernik** [comment]
I tried the framework with a kafka 9 TGZ and it didn't start up troubleshooting now.

**Comment by JohnOmernik** [comment]
This is the error I am getting trying to run Kafka 9

2015-12-07 21:43:43,001 [BrokerServer] WARN  ly.stealth.mesos.kafka.Executor$  -
java.lang.NoSuchMethodException: kafka.server.KafkaConfig.<init>(java.util.Properties)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at ly.stealth.mesos.kafka.BrokerServer$Distro$.startReporters(BrokerServer.scala:91)
        at ly.stealth.mesos.kafka.KafkaServer.start(BrokerServer.scala:45)
        at ly.stealth.mesos.kafka.Executor$.ly$stealth$mesos$kafka$Executor$$runBroker0$1(Executor.scala:76)
        at ly.stealth.mesos.kafka.Executor$$anon$1.run(Executor.scala:98)

**Comment by JohnOmernik** [comment]
Any thoughts on this?

**Comment by dmitrypekar** [comment]
Hi, we are going to investigate / add support of Kafka 9 soon. Need to investigate the above issue.

**Comment by dmitrypekar** [comment]
PR landed in https://github.com/mesos/kafka/pull/168
You can test from it, if you want.

Will be merged and released in a few days.

**Comment by joestein** [comment]
0.9.4.0 released https://github.com/mesos/kafka/releases/tag/0.9.4.0
