### ISSUE TITLE
kafka.common.MessageSizeTooLargeException

### ISSUE THREAD

**Issue by Tracy6465** [mesos/kafka#251]
I use the flume ,send the topic message from kafka to hdfs, when I send  Large amounts of data   to the kafka. there is an error:
 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
kafka.common.MessageSizeTooLargeException: Found a message larger than the maximum fetch size of this consumer on topic ystmo partition 0 at fetch offset 4. Increase the fetch size, or decrease the maximum message size the broker will allow.
    at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:91)
    at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
    at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:11:34 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:11:39 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:11:44 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:11:49 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:11:54 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:11:59 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:12:04 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:12:09 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
16/09/07 16:12:14 ERROR kafka.KafkaSource: KafkaSource EXCEPTION, {}
java.lang.IllegalStateException: Iterator is in failed state
    at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:54)
    at org.apache.flume.source.kafka.KafkaSource.hasNext(KafkaSource.java:248)
    at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:97)
    at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)

**Comment by steveniemitz** [comment]
The kafka consumer has a configuration of the maximum message size that it will fetch, which it seems you've exceeded here.  See max.partition.fetch.bytes [here](https://kafka.apache.org/documentation/#newconsumerconfigs).

For further information I recommend reaching out on the [kafka-users mailing list](https://kafka.apache.org/contact), as this is unrelated to kafka-mesos.
