### ISSUE TITLE
0.9 to 0.10 upgrade: NPE if no broker in cluster

### ISSUE THREAD

**Issue by shangd** [mesos/kafka#283]
Trying to upgrade a 0.9 cluster to 0.10, originally had no broker and 0.10 won't start with NPE. I had to roll it back to 0.9, create a broker and then upgrade succeeded. 

Exception in thread "main" java.lang.NullPointerException
	at ly.stealth.mesos.kafka.json.ClusterDeserializer.deserialize(Model.scala:247)
	at ly.stealth.mesos.kafka.json.ClusterDeserializer.deserialize(Model.scala:242)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
	at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper$class.readValue(ScalaObjectMapper.scala:190)
	at ly.stealth.mesos.kafka.json.JsonUtil$$anon$1.readValue(JsonUtil.scala:27)
	at ly.stealth.mesos.kafka.json.JsonUtil$.fromJson(JsonUtil.scala:42)
	at ly.stealth.mesos.kafka.Cluster$Storage.load(Cluster.scala:79)
	at ly.stealth.mesos.kafka.Cluster$.load(Cluster.scala:66)
	at ly.stealth.mesos.kafka.scheduler.ProductionRegistry.<init>(Registry.scala:68)
	at ly.stealth.mesos.kafka.cli.SchedulerCli$SchedulerCliImpl.handle(SchedulerCli.scala:183)
	at ly.stealth.mesos.kafka.cli.Cli$.exec(Cli.scala:209)
	at ly.stealth.mesos.kafka.cli.Cli$.main(Cli.scala:191)
	at ly.stealth.mesos.kafka.cli.Cli.main(Cli.scala)

**Comment by steveniemitz** [comment]
Good catch!  Thanks!
