### ISSUE TITLE
Unable to Start Brokers  Executor  -  java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by JohnOmernik** [mesos/kafka#288]
Getting the error below when brokers are started. Using the current kafka-mesos and Kafka 0.10.2.0.

[2017-03-08 07:56:23,415] INFO New leader is 1 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
[2017-03-08 07:56:23,503] INFO [Kafka Server 1], started (kafka.server.KafkaServer)
2017-03-08 07:56:23,896 [BrokerServer] WARN  Executor  - 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ly.stealth.mesos.kafka.executor.MetricCollectorProxy.ly$stealth$mesos$kafka$executor$MetricCollectorProxy$$collect(MetricCollectorProxy.scala:49)
	at ly.stealth.mesos.kafka.executor.MetricCollectorProxy.start(MetricCollectorProxy.scala:45)
	at ly.stealth.mesos.kafka.executor.KafkaServer$Distro$.startCollector(BrokerServer.scala:201)
	at ly.stealth.mesos.kafka.executor.KafkaServer.start(BrokerServer.scala:90)
	at ly.stealth.mesos.kafka.executor.Executor$$anon$1.run(Executor.scala:94)
Caused by: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at ly.stealth.mesos.kafka.executor.MetricCollectorProxy$MetricsCollector.collectJvmMetrics(MetricCollectorProxy.scala:111)
	at ly.stealth.mesos.kafka.executor.MetricCollectorProxy$MetricsCollector.run(MetricCollectorProxy.scala:194)
	... 9 more
2017-03-08 07:56:23,899 [BrokerServer] INFO  BrokerServer  - Stopping KafkaServer
[2017-03-08 07:56:23,900] INFO [Kafka Server 1], shutting down (kafka.server.KafkaServer)
[2017-03-08 07:56:23,902] INFO [Kafka Server 1], Starting controlled shutdown (kafka.server.KafkaServer)

**Comment by JohnOmernik** [comment]
Self fix, as of now need to use the v0.10 branch, then it works
