### ISSUE TITLE
failing to start scheduler when kafka broker zk chroot path does not exist

### ISSUE THREAD

**Issue by sherzberg** [mesos/kafka#88]
If the kafka broker zk path is set to something that doesn't yet exist in zookeeper, an exception is raised when connecting here https://github.com/mesos/kafka/blob/master/src/scala/ly/stealth/mesos/kafka/Cluster.scala#L172.

If I am not mistaken, kafka will create that path when the brokers start if the path doesnt exist so should the scheduler create this first similar to https://github.com/mesos/kafka/blob/master/src/scala/ly/stealth/mesos/kafka/Cluster.scala#L165?

**Comment by sherzberg** [comment]
I was mistaken by the second source code link I sent. That looks like it is supposed to create the path, but here is the stack trace I get when the node doesn't exist:

``` bash
I0728 18:49:50.745301    53 sched.cpp:157] Version: 0.22.1                                                                                                                                                        
2015-07-28 18:49:50,746:52(0x7f313d7fa700):ZOO_INFO@check_events@1703: initiated connection to server [172.17.0.232:2181]                                                                                         
2015-07-28 18:49:50,750:52(0x7f313d7fa700):ZOO_INFO@check_events@1750: session establishment complete on server [172.17.0.232:2181], sessionId=0x14ed5fee8290009, negotiated timeout=10000                        
I0728 18:49:50.751054    93 group.cpp:313] Group process (group(1)@172.17.0.238:55398) connected to ZooKeeper                                                                                                     
I0728 18:49:50.751281    93 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)                                                                                               
I0728 18:49:50.751297    93 group.cpp:385] Trying to create path '/mesos' in ZooKeeper                                                                                                                            
I0728 18:49:50.754824    93 detector.cpp:138] Detected a new leader: (id='3')                                                                                                                                     
I0728 18:49:50.754969    91 group.cpp:659] Trying to get '/mesos/info_0000000003' in ZooKeeper                                                                                                                    
I0728 18:49:50.756405    91 detector.cpp:452] A new leading master (UPID=master@172.17.0.235:5050) is detected                                                                                                    
I0728 18:49:50.756604    92 sched.cpp:254] New master detected at master@172.17.0.235:5050                                                                                                                        
I0728 18:49:50.757370    92 sched.cpp:264] No credentials provided. Attempting to register without authentication                                                                                                 
I0728 18:49:50.760180    92 sched.cpp:448] Framework registered with 20150728-184923-3942650284-5050-1-0000                                                                                                       
2015-07-28 18:49:50,765 [Thread-19] INFO  ly.stealth.mesos.kafka.Scheduler$  - [registered] framework:#-0000 master:#050-1 pid:master@172.17.0.235:5050 hostname:mesosmaster.dev.banno.com                        
Exception in thread "Thread-19" org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /kafka-mesos                                  
       at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)                                                                                                                                   
       at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685)                                                                                                                                     
       at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:304)                                                                                                                                                  
       at org.I0Itec.zkclient.ZkClient.createPersistent(ZkClient.java:243)                                                                                                                                        
       at ly.stealth.mesos.kafka.Cluster$ZkStorage.saveJson(Cluster.scala:172)                                                                                                                                    
       at ly.stealth.mesos.kafka.Cluster$Storage.save(Cluster.scala:136)                                                                                                                                          
       at ly.stealth.mesos.kafka.Cluster.save(Cluster.scala:53)                                                                                                                                                   
       at ly.stealth.mesos.kafka.Scheduler$.registered(Scheduler.scala:100)                                                                                                                                       
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /kafka-mesos                                                                                                        
       at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)                                                                                                                                   
       at org.apache.zookeeper.KeeperException.create(KeeperException.java:42)                                                                                                                                    
       at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:643)                                                                                                                                               
       at org.I0Itec.zkclient.ZkConnection.create(ZkConnection.java:87)                                                                                                                                           
       at org.I0Itec.zkclient.ZkClient$1.call(ZkClient.java:308)                                                                                                                                                  
       at org.I0Itec.zkclient.ZkClient$1.call(ZkClient.java:304)                                                                                                                                                  
       at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675)                                                                                                                                     
       ... 6 more
```

This is my zk connection `--zk=zookeeper:2181/kafka`. I am not sure where the `/kafka-mesos` comes from as that is what I get no matter what `--zk` I provide.

**Comment by sherzberg** [comment]
Figured out that `/kafka-mesos` comes from `--storage`. So I changed my settings to:

```
zk=zookeeper:2181
storage=zk:/kafka
```

and now things seem happier. I'm trying to debug the scheduler now to see if I can figure out why this change now works.

**Comment by dmitrypekar** [comment]
Hi, fixed those issue with "missing chroot path for zk storage" in latest release 0.9.1.4.
Thank you for your feedback. Please try it out and close this issue if it helps.

**Comment by sherzberg** [comment]
@dmitrypekar :100: thanks for the quick turnaround! https://github.com/mesos/kafka/commit/baec260aab391d1333d1f47b48ec0afbacb4f80d fixes this issue.
