### ISSUE TITLE
Unclear on starting broker -- jar locations don't seem correct

### ISSUE THREAD

**Issue by memelet** [mesos/kafka#99]
I am running the schedule via marathon:

```
    - role: marathon_app
      marathon_app:
        id: "/ops/kafka-mesos-scheduler"
        cmd: >-
          ./kafka-mesos.sh scheduler
          --storage zk:/kafka-mesos
          --master zk://zookeeper.service.consul:{{zookeeper_client_port}}/mesos
          --zk zookeeper.service.consul:{{zookeeper_client_port}}
          --api http://zookeeper.service.consul:7000
        cpus: 0.1
        mem: 128
        instances: 1
        uris:
          - https://s3.amazonaws.com/si-vpc-internal/vimana/ops-kafka-mesos/kafka-mesos-{{ version }}.tgz
```

Where kafka-mesos.tgz contains:
- kafka-mesos-0.9.1.1.jar
- kafka-mesos.sh
- kafka_2.10-0.8.2.1.tgz

The schedule starts with no errors that I can find.

Then I start a broker:

```
curl "http://localhost:7000/api/brokers/add?id=0&cpus=2&mem=2048"
curl "http://localhost:7000/api/brokers/start?id=0"
```

But the task started by the schedule seems to want to download artifacts from zookeeper.

```
I0809 04:02:39.610327  2428 fetcher.cpp:214] Fetching URI 'http://zookeeper.service.consul:7000/jar/kafka-mesos-0.9.1.1.jar'
I0809 04:02:39.610530  2428 fetcher.cpp:125] Fetching URI 'http://zookeeper.service.consul:7000/jar/kafka-mesos-0.9.1.1.jar' with os::net
I0809 04:02:39.610546  2428 fetcher.cpp:135] Downloading 'http://zookeeper.service.consul:7000/jar/kafka-mesos-0.9.1.1.jar' to '/mnt/mesos/slaves/20150522-122903-2693333002-5050-7694-S24/frameworks/20150522-122903-2693333002-5050-7694-0000/executors/broker-0-a65870ff-f951-473e-bd26-6e46ae61baf0/runs/502ed53b-85e5-45ef-a62d-fea9f0086fdc/kafka-mesos-0.9.1.1.jar'
E0809 04:06:56.432394  2428 fetcher.cpp:138] Error downloading resource: Couldn't connect to server
Failed to fetch: http://zookeeper.service.consul:7000/jar/kafka-mesos-0.9.1.1.jar
Failed to synchronize with slave (it's probably exited)
```

It seems like the schedule is getting its state from zookeeper correctly.

```
$ curl "http://localhost:7000/api/brokers/status?id=0"
{"brokers" : [{"stickiness" : {"period" : "10m", "stopTime" : "2015-08-09 04:12:07.067"}, "id" : "0", "mem" : 2048, "cpus" : 2.0, "heap" : 1024, "failover" : {"delay" : "1m", "maxDelay" : "10m"}, "active" : false}], "frameworkId" : "20150522-122903-2693333002-5050-7694-0000"}
```

Have I misconfigured something?

**Comment by memelet** [comment]
I think maybe I don't understand the meaning of --api or what address that should refer to...

**Comment by memelet** [comment]
Ok, I see what is going on. --api really needs to the be marathon assigned HOST.

Now I am at

```
2015-08-09 07:13:59,586 [Thread-92] INFO  ly.stealth.mesos.kafka.Scheduler$  - [statusUpdate] broker-0-4aa424b4-ab0e-4c12-b5fe-18611388a9d4 TASK_FAILED slave:#4-S25 reason:REASON_COMMAND_EXECUTOR_FAILED message:java.lang.ExceptionInInitializerError
    at ly.stealth.mesos.kafka.KafkaServer.start(BrokerServer.scala:43)
    at ly.stealth.mesos.kafka.Executor$.ly$stealth$mesos$kafka$Executor$$runBroker0$1(Executor.scala:76)
    at ly.stealth.mesos.kafka.Executor$$anon$1.run(Executor.scala:98)
Caused by: java.lang.IllegalStateException: Kafka distribution dir not found
    at ly.stealth.mesos.kafka.BrokerServer$Distro$.init(BrokerServer.scala:112)
    at ly.stealth.mesos.kafka.BrokerServer$Distro$.<init>(BrokerServer.scala:73)
    at ly.stealth.mesos.kafka.BrokerServer$Distro$.<clinit>(BrokerServer.scala)
    ... 3 more
```

Where would the kafka distribution dir be set? I don't see any mention of it in the docs.

**Comment by memelet** [comment]
Just missing port 7000 on the slave security-groups... Broker is running now!
